@cijene_scraper_HostAddress = http://localhost:5276

POST {{cijene_scraper_HostAddress}}/api/scraper/start/konzum
Accept: application/json
###

POST {{cijene_scraper_HostAddress}}/api/scraper/start/spar?force=true
Accept: application/json
###

POST {{cijene_scraper_HostAddress}}/api/scraper/start/spar
Accept: application/json
###

GET {{cijene_scraper_HostAddress}}/api/prices?dates=2025-07-04
Accept: application/json
###

GET {{cijene_scraper_HostAddress}}/api/prices/CheapestLocation?barcode=8445290308238&date=2025-07-04
Accept: application/json
###

GET {{cijene_scraper_HostAddress}}/health
###